name: stereo-skills-py-spacel3d-mesh
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - h5py
  - pillow
  - imageio
  - anndata
  - open3d
